images:
  - image: nginx:latest
    platform: linux/amd64
    enabled: false
    pushName: gcr.io/$PROJECT_ID/$REPO_NAME
  - image: eclipse-temurin:8u432-b06-jdk-focal
    platform: linux/amd64
    enabled: false
    pushName: eclipse-temurin:8u432-b06-jdk-focal2
  - image: tomcat:9.0.91-jdk8-temurin-focal
    platform: linux/amd64
    enabled: false
    pushName: tomcat:9.0.91-jdk8-temurin-focal
  - image: alpine/socat:latest
    platform: linux/amd64
    enabled: true
    pushName: alpine/socat:v1.0.0

runtimes:
  - folderPath: base/libs-sources
    imageName: zengo1209/dockerlibs-sources
    enabled: true
  - folderPath: base/libs-jemalloc
    imageName: zengo1209/dockerlibs-jemalloc
    enabled: false
  - folderPath: base/libs-ffmpeg5
    imageName: zengo1209/dockerlibs-ffmpeg5
    enabled: false
  - folderPath: base/libs-ffmpeg6
    imageName: zengo1209/dockerlibs-ffmpeg6
    enabled: false
  - folderPath: base/libs-java-agent
    imageName: zengo1209/dockerlibs-java-agent
    enabled: false

dockerFiles:
  - folderPath: java/jdk8
    imageName: jdk8-debian
    enabled: false
    pushTag: "" # 空字符串表示 使用 $imageName:$date-$rand[4] 作为tag
  - folderPath: java/jdk8-ffmpeg
    imageName: jdk8-debian-ffmpeg
    enabled: false
    pushTag: "" # 空字符串表示 使用 $imageName:$date-$rand[4] 作为tag
  - folderPath: java/jdk8-ffmpeg-copy
    imageName: jdk8-debian-ffmpeg-copy
    enabled: false
    pushTag: ""
  - folderPath: java/jdk8-arthas-server
    imageName: jdk8-debian-arthas-server
    enabled: false
    pushTag: "v0.0.4"
  - folderPath: java/jdk21
    imageName: jdk21-ubuntu-22.04
    enabled: false
    pushTag: ""
  - folderPath: java/jdk21-jemalloc
    imageName: jdk21-jemalloc-ubuntu-22.04
    enabled: false
    pushTag: ''