services:
  searxng-server:
    image: searxng/searxng
    container_name: searxng
    restart: always
    ports:
      - 8899:8899
      - 8080:8080
    environment:
      - INSTANCE_NAME=searxng-local
      - BIND_ADDRESS=0.0.0.0:8899
      - BASE_URL=http://localhost:8899
    volumes:
      - ./searxng:/etc/searxng