# base image
FROM python:3.10.15-slim-bookworm

ENV TZ=UTC

WORKDIR /app/
ENV PUPPETEER_SKIP_DOWNLOAD=true

# 1. Install Linux packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    curl \
    wget \
    vim \
    ffmpeg \
    libgmp-dev \
    libmpfr-dev \
    libmpc-dev \
    pkg-config \
    libseccomp-dev \
    libc-dev \
    libffi-dev \
    tcpdump \
    htop \
    pandoc \
    npm nodejs chromium fonts-noto-cjk fonts-liberation \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && npm install -g @mermaid-js/mermaid-cli \
    && npm cache clean --force \
    && mmdc --version