services:
  jdk8:
    image: dockerlibs:jdk8-v0.0.1
    container_name: jdk8
    volumes:
      - ./spring-demo-start-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./entrypoint.sh:/app/entrypoint.sh

    environment:
      #JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7091 -Dcom.sun.management.jmxremote.rmi.port=7091 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false  -Djava.rmi.server.hostname=127.0.0.1 -Xmx512m -Xms512m -Djava.security.egd=file:/dev/./urandom"
      JAVA_OPTS: "-Xmx512m -Xms512m -Djava.security.egd=file:/dev/./urandom"

    command: ["/app/entrypoint.sh"]
    # command: ["/bin/sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
    ports:
      - "8080:8080"
      - "7091:7091"