services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    restart: always
    hostname: "minio-local"
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=demo
      - MINIO_ROOT_PASSWORD=demodemo
    ports:
      - 9000:9000
      - 9001:9001