services:
  grafana:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    hostname: "rabbit-local"
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=superadmin
      - RABBITMQ_DEFAULT_PASS=ECr7ZcUl64cmfJtLqqpj
      - RABBITMQ_DEFAULT_VHOST=digitaltwin-prod
    command: >
      /bin/bash -c "cp /opt/plugins/* /plugins/ && rabbitmq-plugins enable rabbitmq_delayed_message_exchange --offline && rabbitmq-server"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./plugins:/opt/plugins

# 进入到容器中 rabbitmq-plugins enable rabbitmq_delayed_message_exchange 启用插件
# /bin/bash -c "
# rabbitmq-plugins enable rabbitmq_delayed_message_exchange --offline &&
# rabbitmq-server"